[workspace]
resolver = "2"
members = ["crates/pe-rs", "crates/pe-rs-gui"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["aphage"]
repository = "https://github.com/aphage/pe-rs"

[workspace.dependencies]
thiserror = "2"
bytemuck = { version = "1", features = ["derive"] }
