[package]
name = "pe-rs"
description = "PE (Portable Executable) file viewer/editor library with Scylla-style import-table rebuilding (IAT fix) support."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
iced-x86 = "1.21.0"
thiserror.workspace = true
windows-sys = { version = "0.61.2", features = [
    "Win32_System_SystemServices",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemInformation",
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_ProcessStatus",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
] }

[dev-dependencies]
