//! Round-trip guarantees of the real parser/writer:
//! `parse(serialize(doc))` must preserve the document's content.

mod common;

use pe_rs::io::pe::{parse, serialize};

#[test]
fn serialize_then_parse_preserves_imports() {
    let orig = common::doc_via_mock();
    let bytes = serialize(&orig).unwrap();
    let reparsed = parse(&bytes).unwrap();
    assert_eq!(reparsed.imports, orig.imports);
}

#[test]
fn serialize_then_parse_preserves_headers_and_exports() {
    let orig = common::doc_via_mock();
    let bytes = serialize(&orig).unwrap();
    let reparsed = parse(&bytes).unwrap();
    assert_eq!(reparsed.arch, orig.arch);
    assert_eq!(reparsed.dos, orig.dos);
    assert_eq!(reparsed.coff.machine, orig.coff.machine);
    assert_eq!(reparsed.coff.characteristics, orig.coff.characteristics);
    assert_eq!(reparsed.optional.image_base(), orig.optional.image_base());
    assert_eq!(
        reparsed.optional.address_of_entry_point(),
        orig.optional.address_of_entry_point()
    );
    assert_eq!(reparsed.optional.section_alignment(), orig.optional.section_alignment());
    assert_eq!(reparsed.exports, orig.exports);
}

#[test]
fn serialize_then_parse_preserves_section_content() {
    let orig = common::doc_via_mock();
    let bytes = serialize(&orig).unwrap();
    let reparsed = parse(&bytes).unwrap();
    for s in &orig.sections {
        let name = s.name_str();
        let found = reparsed
            .sections
            .iter()
            .find(|x| x.name_str() == name)
            .unwrap_or_else(|| panic!("section {name} missing after round-trip"));
        assert_eq!(found.data, s.data, "section {name} data differs");
        assert_eq!(found.header.virtual_address, s.header.virtual_address);
    }
}

#[test]
fn serialize_then_parse_produces_reparseable_import_directory() {
    let orig = common::doc_via_mock();
    let bytes = serialize(&orig).unwrap();
    let reparsed = parse(&bytes).unwrap();

    // The rebuilt import directory must be readable through the document, i.e.
    // the generated bytes really form a valid descriptor/thunk/name table.
    let import_dir = reparsed.data_directory(pe_rs::domain::DataDirectoryIndex::Import).unwrap();
    assert_ne!(import_dir.rva, pe_rs::domain::Rva::NULL);
    assert!(import_dir.size > 0);
    assert_eq!(reparsed.read(import_dir.rva, import_dir.size as usize).map(|b| b.len()).unwrap_or(0), import_dir.size as usize);
}

#[test]
fn double_roundtrip_is_stable() {
    let orig = common::doc_via_mock();
    let once = parse(&serialize(&orig).unwrap()).unwrap();
    let twice = parse(&serialize(&once).unwrap()).unwrap();
    assert_eq!(once.imports, twice.imports);
    assert_eq!(once.exports, twice.exports);
    assert_eq!(once.sections.len(), twice.sections.len());
}

#[test]
fn rejected_truncated_input() {
    let bytes = b"MZ\x90\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00";
    assert!(parse(bytes).is_err());
}

#[test]
fn rejected_non_pe() {
    let mut bytes = vec![0u8; 0x100];
    bytes[0] = b'M';
    bytes[1] = b'Z';
    // e_lfanew defaults to 0 -> no PE signature there.
    assert!(parse(&bytes).is_err());
}
